language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: boaz-69
  api_key:
    secure: DsptxbG9ROekHvYTYKm6d80yaAQpXSRrsPj2unf4G2fWnnpghc/V9Kz+pIogfvKu8e+1HMc+dW+YwN5a6zCcjkDGg2Hp59TQeSqBajrgqoEiyEb/BTPSa5cvh//5fPI1H1af4pNn37kjICBNtYunVykl704q0nGUTeD26u9Y8/t+jFv5CBfUPZHoV+o76sq5BMhaAkIHkf4kYmAJsnTDOquaV4bAdv/AHgGlSBxShfalrbBIpI8WU8m7c/P5Y5rz32e0yQcRrLOdRK25y9F4o02D63vNSUp7291Cq4CS9KU+P24dU0AJraKtf7jIFa7zk/G1PbCVo6PWbH4Q1AHjtaSRMdKSsQ1ySLHQhx8Xfs2QtC959kKmdWAcvogpmNusa2sfJr/PYMHkW/jSCIYadk/pDbDMZ8xKBLgdZJd48Em5QJWrSjRxGakLYxuaH0AsMgwsaVR+Z6rd6wTRUGXVK9+STNS7QCmvPkGonz8/e9W9Hy0ngrgFuTA/J2H1EoYVceVPPqvt3SILYvankhhPJqpwDyouxICeIeCV/kwzaQA3ibLfcfLyhMj0IGGndV6Ma1Scbbtyhmr2O8zDc5d/c3m0oVtMBRj+EhunxQUSKPyJFak4MWnTIWOE4KjOeRYMvKtN52ceqzhuhTfxMCMC7hQwax1wjszQ0aB4ziSvZtE=
