language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: boaz-69
  api_key:
    secure: P8wmHPeC98+d1aP9yFy/Mcn67nn1GyLO3LCSmMu0s1ckXAFc/VgkmCZ9v1p7hSwHB/TLvXLuugVPXzcwwmgkDpz9WD21asf1Ol2a2tBVk04pD9GSrQSZlBioTnguoO74vFAwM6gYNmRaUqEbcQTbu6OvmRGeKRRcwMKQLdHNt6RsYNNPmp/Oj/EYm1zR4/IgRJvJmBdoP/ynnv+YYiJHNQ9+qRyCByYXuC9eYPMhhnFAqZZ32WbAiOtUHC7AzOdxHlyn40OFHjHYZM+shkb+9NELUjudZX7cbJKpz8/brfnCC7l/iLkF8MbE6Q+5F5BhCrGsVadKF6qUnVXmgQzWDgFsP38x5LxiojT1PLWhX8/N1nLlcW070FzBoO2B0KH7WwTt7d4lsdjGP3kYC4NBvehPdRsjXC+mh4EkuwDGaKKrdA3ojJ2SAI7oJZelcT+Y1Rl1I8yuOTcLYiWCXOtDJsmr+mRMX4cwdY0hV0FYTIYSATGXN/mt8NCOH7K+PG0+Oo8QbCpn1m0ifrdiSwyA22hSpzIjWJ13ztGZOl6JvPt7ufJugukp7yHupZvre1CPqYP07IVNakJZjJv4jw0QbUjZFs0MnmrjsrjT7MUIeTzhXfrbQrtSZQzUzIpp/Mz81YJk4czsFvxbnhD/l8zm+/Gci5liZZRTXrMg5IKPQWU=
