language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: m/I1sFobIOi5gpn5xPX458l+yrdllbwddQ9IxMrjVAUthkUCKBFCskek7uA5gXhSbwnRyNDsOTUDKYvhsBlIrnJ9INPTVsWs4TGwUjhr3a1qaCRPU99KQ09U6oh4wzMqAkzSuhg0BHNY606epmyINz81e3ugwzJ+p5CG0WCVHVxTNpqzZN4QBVCoDfCzLPkyLBOSp6MHepwJMfmfGOe9aX5QYy1WKWyQKvDALeXfe7RXRzV65G4mdbt5YtJEVQRGF15TjKei6N31lzLvDGge/jrlf1QgVvc0g4GYvgc7QUs5oy5Ob643G3gXXXp+Ipz4Ff7rurRGEpEzkJBQB4lkW0qZrJdyKteg4UV/ZyuHxi66DRzEbl+k+cxzHlnniz3O0Jg4SLsxo26CsbvjRteNu2s+bJEbKlo0Bu7c0j2V8rwNz2mE78TavWE3qTGmRJ9YkH4JTFS8V92KvZbUxReLhJeM/mUXv+t6XRcutnNSAwuTBI48U43QkNMh/mS5tLqz7jifKL7W9M9cqGNpw4+eUUMinxLSbONEl9VA7q0yIC7FinWIeoFn6HKO+7YTc/k7c8G8jGNRzTgFXets0K5XJEIYsEaPv7dogUeciOxZX9x+iPh/6VtaKu2jtHzRm378OXESSf9saBb/jAxC4tiHWTcSxCc0YXjuwbmOZnp1sl0=
