language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: boaz-69
  api_key:
    secure: 4g0hefMlI1meyJJdkAixrpA6j5dLCT5jF2la3MWwWhbmXHn99nUQAsJHj3O5EptDL/K70jbW2WbgpwHiIv69XrOiAqBIPAJDsFiRPWgHXdUASM0Do6KsNzDJbR8LMawGjgoBxbp9Gn62xHhKAXj2xafV4uq3MwWsAcNWP3ZbQ7vrfVnycJNQegNlnIo+8vASHN1JD3KBYstsV29ksRvkIycRC5tw9OH1Tjd8OYS89SeH8n84e0/nEWx9H8IeWHor9E9ZFsiAYcHi8rwp9V38ofixM0/SUDnDCse03U94Y1lPhgbtFy4pa3+FUgewnHcb2PY4xoZoMRdMwF+OGZrSBWfENEw+kA3LgNsloimifZoaipdFGD3bu0ikidlQL7BJHaweKHAF5pUnZW0G6cZ29pftxBnsLTUHp0z5lwlJzEMBOGlmgsJv9iujYm67D6uyzJ3FEJ2I3aTperOdSLiZkoTOLwxFKB+FT01JDsqq4TVfzBNCa5OcXfhXNm47zIU5iD0FTRcPCLABTV+VNFG6CCn9RMz0qS/1Rc4YjzMBoBJRcG5ww2AH5oolkvy79GofBNvT+6MdmL/vuDIMAGI1cS343mjpRYdms/hieOcorJitSJkp2J2/G2fUhQKbdx78KezKDkM28AMJ/1K3s14/oL/ptyJU9VFPl0Alx8JRKQ0=
